### ISSUE TITLE
Clear ports before forwarding them

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/go-upnp#1]
We should clear the current port mapping before adding the new one. If an error is returned, it can be ignored.

**Comment by lukechampine** [comment]
Actually, it's probably better to do this outside the library.

**Comment by DavidVorick** [comment]
Do you mind explaining your thoughts more?

**Comment by lukechampine** [comment]
This package (primarily) exposes two simple operations: `Forward` and `Clear`. Making `Forward` invisibly call `Clear` would be surprising behavior.

Then again, most people would probably want that behavior, and this package _is_ supposed to be opinionated...hmm.

**Comment by DavidVorick** [comment]
Nah seems good enough to keep them fully separate.

**Comment by lukechampine** [comment]
Perhaps an `Entry(uint16) string` method would be useful: it would return the description of the mapping of the specified port. Then you could more intelligently determine whether to clear or forward the port. E.g:

``` go
switch d.Entry(9001) {
case "Sia":
    // already mapped
    return
case "":
    // not yet mapped
    d.Forward(9001, "Sia")
default:
    // mapped by a different program
    d.Clear(9001)
    d.Forward(9001, "Sia")
}
```

**Comment by DavidVorick** [comment]
Should the behavior ever be to clear a port that was mapped by a different process? Also what if a different siad is using the port?

**Comment by lukechampine** [comment]
I suppose not, unless you want to be a jerk to that process. Better to return an error.
The latter case is trickier, since the info above (just the port + description) is not sufficient to know whether you mapped the port or another siad did. You'd need to know the destination IP as well, and compare it with your own.
