### ISSUE TITLE
Retrieve existing Port Forwardings

### ISSUE THREAD

**Issue by frennkie** [NebulousLabs/go-upnp#14]
It would be nice to be able to check/retrieve the currently configured Port Forwardings/Mappings.

According to http://upnp.org/specs/gw/UPnP-gw-WANIPConnection-v1-Service.pdf there are two methods for this  `GetGenericPortMappingEntry` (iterate all existing forwardings) and `GetSpecificPortMappingEntry` (limited to a set of ext IP, ext Port, Protocol).

Any chance this could be implemented? I would try to work on a PR but I have no experience with Go at all .. :-/

**Comment by lukechampine** [comment]
Agree, this would be a good feature. But also disagree -- I think you could do this! :)

Basically all you have to do is add a method on IGD that calls `d.client.GetSpecificPortMappingEntry`. The rest is just designing the API and passing arguments around. So take a stab at it; even if it doesn't compile, I'll help you clean it up and we'll get it merged.

**Comment by lukechampine** [comment]
Fixed in #15
